### ISSUE TITLE
🚀 1.2

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#581]
This is a superissue to aggregate and prioritize issues and PRs currently in the works

https://github.com/neherlab/covid19_scenarios/milestone/3

### - Uncertainty of parameters

Some parameters are now ranges `{min, max}`. Results are now a distribution `[{mean, lower, upper}]`

   - [x] algorithm #537
   - [x] UI/UX: #580
       - [x] number of runs are adjustable (with spinbox)  #599
       - [x] ~run progress indicator~ looks like this cannot be done for the computation on the same-thread. Maybe with webworkers or something like redux-saga?
       - [x] better sliders and/or spinboxes  for R0 and Mitigation #604 
       - [x] validate the new range spinboxes
   - [x] long and short runs: #582 __
       - [x] spinbox for number of runs  #599
       - [x] spinbox limit min to 10
       - [x] run in a webworker  #505 
   - [x] better plots
       - [x] tooltips - layout numbers as a tuple
       - [x] better print preview table

### - Mitigation presets

Mitigation table should be populated with real data

  - [ ] Issue: #347
  - [ ] PR: #426 
  - [ ] TODO: Clarify the next steps.

### - Parameter upload

Currently scenarios can be shared via URL. It is not perfect and we constantly have problems with it. File sharing would be another option.

 - [x] Proper JSON export: all parameters required to exactly (barring the uncertainity) reproduce a run should be present, and nothing more
 - [x] New JSON import (it should reproduce the exported run)
 - [x] New UI/UX for import
       [x] Dialog instead of scenario dropdown: #397 #490
       [x] JSON Import: #541
       [ ] Better styling for import window and dropbox

 - [ ] Better UX for JSON export
 - [x] Proper serialization and validation against JSON schema
 - [ ] Proper error handling and error dialogs
 - [x] Versioning

### - Double-check URL validation and add error dialogs

Currently errors in URL import are are silent for the user

 - [ ] https://github.com/neherlab/covid19_scenarios/issues/573

###  - Automatic data updates
 - [ ] https://github.com/neherlab/covid19_scenarios/issues/521

 ### - Algorithm in a webworker
  - [x] https://github.com/neherlab/covid19_scenarios/pull/505
  - [x] Watch out for concurrency bugs!

### - Fix remaining type issues and enable build-time type checking
 - [x] https://github.com/neherlab/covid19_scenarios/issues/512

### - Translations

 - [x]  Gitlocalize is now in place. But it is unclear what has to be done next.
 - [ ] English strings need to be updated for the uncertainty feature
 - [ ] find translators?
 

### - Additional details in PDF
 - [ ] https://github.com/neherlab/covid19_scenarios/issues/488
 - [ ] add MDX component when large paragraphs are needed, to simplify editing
 - [ ] pass props to MDX and render dynamic paragraphs (with variables inserted etc.)
 - [ ] add more content

### - Improve error pages
 - [ ] https://github.com/neherlab/covid19_scenarios/issues/425

**Comment by noleti** [comment]
regarding the sharing of scenarios via URL: could you maintain a simple cache/hash table (probably separate from the app server) to essentially have random keys and parameters as values? Then URL references could be like https://covid19-scenarios.org/Aeif13D, the app would use the Aeif13D key to pull the parameter JSON string from the hash table, and we would have nice shareable short links? entries could be evicted after a while (or if possible, after they haven't been queried for x days). I only used redis a while back, and one would have to do the math to see how much data would be stored in the DB/day etc.

**Comment by nnoll** [comment]
@noleti this is what I imagine as well.

**Comment by noleti** [comment]
another maybe: localization? We would a) need enough translations (and verify they currently catch everything needed), b) see that it works in the current UI

**Comment by ivan-aksamentov** [comment]
@noleti 

Regarding the URL suggestion, we thought about it previously. This is basically a URL shortener service (like `goo.gl`, `t.co` and `bit.ly`), except we need to fetch value from there in the response body, bypassing the URI. However it only workarounds the problem. Plus the need of maintaining the online service. We thought file-based solution is somewhat more "final". But we can discuss that, of course.

Regarding translations, I don't know what has to be done. In order to translate, we need English version to be finalized. But it's never final because we change everything every day. So I guess the translations have to be done in an incremental fashion. But that's kinda annoying for the translators.

**Comment by noleti** [comment]
In my view, there are two distinct target audiences: "consumers" and "pros". The former will just look at a graph for their country, and not play with values too much (at most starting infected, ICU beds, and R0/ mitigations). The latter might want to try many different scenarios, seasonal influence, severity assumptions, age distributions, etc. For the former, scenario sharing should be as easy as possible, i.e. the hash in the URL, lookup from DB by our API. The latter user group will be more comfortable with downloading files, changing or generating files on their side, and re-simulating based on the files. That audience would also need more API capabilities (e.g., just return results, plot.png, pdf based on uploaded file). Once they have settings they want to share, they could just use the URL shortener again.

I don't really see the issue with sharing the same DB for stable and testing instances, as long as the DB is key/value store (e.g. Redis). If keys are all pseudo-random, the instances should(TM) not interact? If you start to use a nosql DB with schemas etc (e.g., MongoDB), things will get more complicated I guess (i.e. new versions require new schemas). Or do you mean SQL with "normal database"? There would be the same schema issues I guess?

Storage-wise: I'm not sure how many users you have daily, but lets assume 1M. If each scenario settings needs 3kB (current settings export), then this would be 3GB. But the current settings have some crazy float precision (and pretty printing), so maybe 1kB/setting is more realistic. Given that many users will concentrate on few countries and default settings, I assume using a hash of the settings as key will lead to further storage reduction. So the database would maybe need 10GB if values are kept for a week (more to be on the safe side). cache.r4.large aws instances with 12 GB RAM cost about 150 USD/month? So key:value cashing with minimal REST API boilerplate on your server seems feasible to me. Not that I am volunteering to write the code though.

Regarding translation: I think we will have to live with the risk of having some untranslated strings. The Gitlocalize should make it easy for people to contribute, though. We just need to write some instructions/advertise this (If we want to use localization soon). I think we should also start to use "placeholder/ID" strings in the app code, and have the actual text in the EN translation files. but I didn't dig into this yet.

**Comment by ivan-aksamentov** [comment]
@noleti  By "normal database" I mean whatever stores data in a typed format, not just a string of serialized JSON (which our URLs are). For shortener, hosting or storage cost should not be a problem.

Why do we need to use placeholders in the app? Won't English text do for  placeholders? It seems to be working alright so far.

**Comment by noleti** [comment]
Re: placeholders. The way I understand the localization setup from https://github.com/neherlab/covid19_scenarios/pull/494 is as follows: we extract strings from the .ts/.tsx files, and generate these dicts from the strings. the dicts currently are setting the value to key by default. This means that if we change the original string a bit, a new key will be generated and needed to be translated in all languages. If instead we use placeholders, we can decide if the english string only changed a bit (and keep the placeholder and all existing translations), or if the meaning is so different a new translation needs to be done (by introducing a new placeholder). Does that make sense? I am not used to i18n, so I might misunderstand things.

**Comment by davihans** [comment]
@ivan-aksamentov Is this what you had in mind for the tooltip layout? 

![tooltip_tuple](https://user-images.githubusercontent.com/17601012/79827909-91434400-836d-11ea-857b-c6891a2a28a2.png)

**Comment by whiver** [comment]
@noleti @ivan-aksamentov I agree for the localization, this would be great to re-enable the language dropdown. Because there is no point in updating the translations if we don't use them.

For the debate between using real strings as keys / using IDs to reference translated strings in the code: I see your point about – modifying translated text in the code also changes the key used for other languages. The problem with using keys is that if you decide to update a text in English, the other languages will still have the old translated version, which could not be relevant anymore if the text changed a lot. Worse: in gitlocalize, you won't easily see that a translation isn't up to date. On the contrary, by using directly the string as key, it also removes the translation, avoiding the risk of having translation mismatchs.

That said, I understand that it's not perfect: if you remove a space in the code, every corresponding translation will be reset. But I still think this is the best tradeoff for now. Maybe another translation platform than Gitlocalize could spot outdated translations, but that's not the case right now :/

**Comment by ivan-aksamentov** [comment]
@davihans I am not sure. We need to ask @nnoll. Also this may influence the format: #613

**Comment by nnoll** [comment]
I think we should just report the percentiles as absolute numbers, not
plus/minus the median. I like your suggestion of (low, <b>median<b>, high)

**Comment by ivan-aksamentov** [comment]
Uncertainty is released in 1.2
Import will be released in 1.3 shortly: https://github.com/neherlab/covid19_scenarios/milestone/4
The remaining is moved further on the timeline.

**Comment by psaux01** [comment]
> Este es un super tema para agregar y priorizar problemas y relaciones públicas actualmente en proceso
> 
> https://github.com/neherlab/covid19_scenarios/milestone/3
> 
> ##  Características principales
> ### - Incertidumbre de los parámetros.
> Algunos parámetros son ahora rangos `{min, max}`. Los resultados ahora son una distribución`[{mean, lower, upper}]`
> 
> * [x] algoritmo [# 537](https://github.com/neherlab/covid19_scenarios/pull/537)
> * [x] UI / UX: [# 580](https://github.com/neherlab/covid19_scenarios/issues/580)
>   
>   * [x] Número de carreras ajustables (con spinbox)   [# 599](https://github.com/neherlab/covid19_scenarios/pull/599)
>   * [x]  ~ejecutar indicador de progreso~Parece que esto no se puede hacer para el cálculo en el mismo hilo. ¿Quizás con trabajadores web o algo así como la saga redux?
>   * [x] mejores controles deslizantes y / o spinboxes para R0 y Mitigación [# 604](https://github.com/neherlab/covid19_scenarios/pull/604)
>   * [x]  validar la nueva gama spinboxes
> * [x] carreras largas y cortas: [# 582](https://github.com/neherlab/covid19_scenarios/issues/582) __
>   
>   * [x] spinbox para el número de carreras   [# 599](https://github.com/neherlab/covid19_scenarios/pull/599)
>   * [x]  spinbox limit min a 10
>   * [x] correr en un trabajador web   [# 505](https://github.com/neherlab/covid19_scenarios/pull/505)
> * [x]  mejores parcelas
>   
>   * [x]  información sobre herramientas: números de diseño como una tupla
>   * [x]  mejor tabla de vista previa de impresión
> 
> ### - Presets de mitigación
> La tabla de mitigación debe rellenarse con datos reales.
> 
> * [ ]  Issue: #347
> * [ ]  PR: #426
> * [ ]  TODO: Clarify the next steps.
> 
> ### - Parameter upload
> Currently scenarios can be shared via URL. It is not perfect and we constantly have problems with it. File sharing would be another option.
> 
> * [x]  Proper JSON export: all parameters required to exactly (barring the uncertainity) reproduce a run should be present, and nothing more
> * [x]  New JSON import (it should reproduce the exported run)
> * [x]  New UI/UX for import
>   [x] Dialog instead of scenario dropdown: #397 #490
>   [x] JSON Import: #541
>   [ ] Better styling for import window and dropbox
> * [ ]  Better UX for JSON export
> * [x]  Proper serialization and validation against JSON schema
> * [ ]  Proper error handling and error dialogs
> * [x]  Versioning
> 
> ### - Double-check URL validation and add error dialogs
> Currently errors in URL import are are silent for the user
> 
> * [ ]  #573
> 
> ##  Important
> ### - Automatic data updates
> * [ ]  #521
> 
> ### - Algorithm in a webworker
> * [x]  #505
> * [x]  Watch out for concurrency bugs!
> 
> ### - Fix remaining type issues and enable build-time type checking
> * [x]  #512
> 
> ### - Translations
> * [x]   Gitlocalize is now in place. But it is unclear what has to be done next.
> * [ ]  English strings need to be updated for the uncertainty feature
> * [ ]  find translators?
> 
> ##  Maybe
> ### - Additional details in PDF
> * [ ]  #488
> * [ ]  add MDX component when large paragraphs are needed, to simplify editing
> * [ ]  pass props to MDX and render dynamic paragraphs (with variables inserted etc.)
> * [ ]  add more content
> 
> ### - Improve error pages
> * [ ]  #425
